#ifndef HW_CONFIG_H
#define HW_CONFIG_H

#define LED_R_PIN GPIO_NUM_25
#define LED_G_PIN GPIO_NUM_26
#define LED_B_PIN GPIO_NUM_27
#define MOTOR_CTRL_PIN GPIO_NUM_13
#define FLEX_MID_ADC_CHANNEL ADC_CHANNEL_0 // GPIO36
#define FLEX_IND_ADC_CHANNEL ADC_CHANNEL_3 // GPIO39

#define JOYSTICK_X_CHANNEL ADC_CHANNEL_6 // GPIO34
#define JOYSTICK_Y_CHANNEL ADC_CHANNEL_7 // GPIO35
#define JOYSTICK_BUTTON_PIN GPIO_NUM_15

#define I2C_SDA_PIN GPIO_NUM_9
#define I2C_SCL_PIN GPIO_NUM_10
#define I2C_PORT I2C_NUM_0
#define I2C_CLK_FREQ_HZ 100000

#define LSM6DSOX_I2C_ADDR  0x6A
#define LSM6DSOX_LOW_ADDR_GYRO  0x22
#define LSM6DSOX_LOW_ADDR_ACCEL  0x28

#endif // HW_CONFIG_H